// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Bike struct {
	ID        string `json:"_id"`
	Name      string `json:"name"`
	IsNewBike bool   `json:"isNewBike"`
}

type NewBike struct {
	Name      string `json:"name"`
	IsNewBike bool   `json:"isNewBike"`
}
