// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Bike struct {
	ID         string `json:"_id"`
	Name       string `json:"name"`
	IsGoodBike bool   `json:"isGoodBike"`
}

type NewBike struct {
	Name       string `json:"name"`
	IsGoodBike bool   `json:"isGoodBike"`
}
